#cloud-config
# Keep an extra new line with no spaces for merging files together
packages:
  - git

write_files:
# conf.json
  - content: |
      {
          "--block-disk": "/dev/oracleoci/oraclevdb",
          "--block-path": "/u01/app/oracle/product",
          "--conf": "/u01/app/ioco/conf.json",
          "--cust-yaml": "/u01/app/ioco/dpk/psft_customizations.yaml",
          "--dpk-patch": null,
          "--dpk-platform": "linux",
          "--dpk-source": "CM",
          "--dpk-type": "FS",
          "--dpk-version": null,
          "--example-path": "/u01/app/ioco/example",
          "--export": null,
          "--firewall-pia": null,
          "--force": null,
          "--get-dpk": null,
          "--help": null,
          "--home": "/u01/app/ioco",
          "--install-packages": null,
          "--logs": "/u01/app/ioco/logs",
          "--make-file-system": null,
          "--mount": null,
          "--mount-path": "/cm_psft_dpks",
          "--nfs-host": 10.10.1.4,
          "--secret-id": "ocid.something.123131231",
          "--setup-dpk": true,
          "--setup-file-system": null,
          "--verbose": true,
          "access_pwd": "SYSADM",
          "admin_pwd": "Passw0rd_",
          "attach-dpk-files": null,
          "block": null,
          "cm": null,
          "cm_dpk_files_dir": "/cm_psft_dpks",
          "connect_pwd": "peop1e",
          "db_host": "localhost",
          "db_name": "PSFTDB",
          "db_service_name": "PSFTDB",
          "deploy": null,
          "download_threads": 5,
          "dpk": null,
          "dpk_deploy_dir": "/u01/app/oracle/product/dpk",
          "dpk_files_dir": "/u01/app/ioco/dpk",
          "example": true,
          "gw_keystore_pwd": "password",
          "gw_user_pwd": "password",
          "install": null,
          "mainlog": "ioco.log",
          "oci": null,
          "opr_id": "PS",
          "opr_pwd": "PS",
          "patch_id": null,
          "pia_port": "8000",
          "ps_cfg_dir": "/u01/app/oracle/product/hostname/ps_cfg_home",
          "psft_base_dir": "/u01/app/oracle/product",
          "read": true,
          "rundeck": null,
          "undeploy": null,
          "user_home_dir": "/home",
          "vault": true,
          "weblogic_admin_pwd": "Passw0rd#",
          "webprofile_user_pwd": "PTWEBSERVER"
      }                                 
    path: /u01/app/ioco/conf.json
# psft_customization.yaml
  - content: |
      ---
      # defaults generated by ioco
      dpk_location:     /u01/app/oracle/product/dpk
      user_home_dir:    /home
      ps_config_home:   /u01/app/oracle/product/hostname/ps_cfg_home
                      
    path: /u01/app/ioco/dpk/psft_customizations.yaml

runcmd:
  - [sleep 120] # workaround for iscsi until it's added to ioco
  # manual install python dependencies until published in pip
  - [ sh, -c, 'python3 -m pip install docopt requests' ]
  # clone git repo and checkout branch
  - [ sh, -c, 'git clone https://github.com/psadmin-io/ioCloudOps.git /tmp/ioCloudOps' ]
  - [ sh, -c, 'git --git-dir /tmp/ioCloudOps checkout master' ]
  # setup block storage, mount dpk files repo, and deploy dpk
  - [ sh, -c, 'python3 /tmp/ioCloudOps/ioco oci block --make-file-system --mount' ]
  - [ sh, -c, 'python3 /tmp/ioCloudOps/ioco cm attach-dpk-files' ]
  - [ sh, -c, 'python3 /tmp/ioCloudOps/ioco dpk deploy' ]
