#cloud-config
# Keep an extra new line with no spaces for merging files together

write_files:
  # sudoers.d
  - content: |      
      Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
    path: /etc/sudoers.d/secure-path

runcmd:
  - [ sh, -c, 'yum install -y git python-oci-cli' ]
  # setup iscsi block
  - [ sh, -c, 'systemctl enable ocid.service' ]
  - [ sh, -c, 'systemctl start ocid.service' ]
  - [ sh, -c, 'systemctl status ocid.service' ]
  # manual install python dependencies until published in pip
  - [ sh, -c, 'sudo python3 -m pip install docopt requests' ]
  # we have our repo private in github, so hosting internal on gitlab that doesn't have ssl working right 
  - [ sh, -c, 'sudo git config --global http.sslVerify false' ]
  - [ sh, -c, 'sudo git clone https://github.com/psadmin-io/ioco.git /tmp/ioCloudOps' ]
  # local install until it is published
  - [ sh, -c, 'sudo python3 -m pip install /tmp/ioCloudOps' ]
